version: "2"
services:
  corphub-backend:
    image: corphub-backend:latest
    networks:
      - kong-net
    ports:
      - "8082:8082"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  corphub-frontend:
    image: corphub-frontend:latest
    networks:
      - kong-net
    ports:
      - "10001:10001"
    environment:
      NUXT_PORT: 10001
    depends_on:
      - corphub-backend
    links:
      - corphub-backend

  kong-db:
    image: postgres:9.6
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: api-gw
      POSTGRES_USER: kong
      POSTGRES_PASSWORD:

  kong:
    image: kong:1.3.0rc1-centos-oidc
    depends_on:
      - kong-db
    networks:
      - kong-net
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
      - "8443:8443" # Listener  (SSL)
      - "8444:8444" # Admin API (SSL)
    extra_hosts:
      - "outside:192.168.178.230"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: api-gw
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS: oidc

  elasticsearch:
    image: elasticsearch:5
    command: elasticsearch
    depends_on:
      - kong
    networks:
      - kong-net
    environment:
      # This helps ES out with memory usage
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    volumes:
      # Persist elasticsearch data to a volume
      - elasticsearch:/usr/share/elasticsearch/data
      # Extra ES configuration options
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:5
    command: logstash --auto-reload -w 4 -f /etc/logstash/conf.d/logstash.conf
    environment:
      # This helps Logstash out if it gets too busy
      - LS_HEAP_SIZE=2048m
    #volumes:
    # volume mount the logstash config
    # - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      # Default GELF port
      - "12201:12201/udp"
      # Default UDP port
      - "5000:5000/udp"
      # Default TCP port
      - "5001:5001"
    links:
      - elasticsearch

  kibana:
    image: kibana:5
    environment:
      # Point Kibana to the elasticsearch container
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  kopf:
    image: rancher/kopf:v0.4.0
    ports:
      - "8080:80"
    environment:
      KOPF_ES_SERVERS: "elasticsearch:9200"
    links:
      - elasticsearch

networks:
  kong-net:

volumes:
  kong-datastore:
  elasticsearch:
