apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-db-config
  labels:
    app: keycloak-db
data:
  POSTGRES_DB: keycloakdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: keycloak-db-pv-volume
  labels:
    type: local
    app: keycloak-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/keycloak-db/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-db-pv-claim
  labels:
    app: keycloak-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: postgres:12.1
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: keycloak-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-db
      volumes:
        - name: keycloak-db
          persistentVolumeClaim:
            claimName: keycloak-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  type: LoadBalancer
  ports:
   - port: 5432
  selector:
   app: keycloak-db